### ISSUE TITLE
Traceback with the visualising_pluto.py

### ISSUE THREAD

**Issue by jj-gonzalez-aviles** [predsci/PsiPy#38]
I am trying to visualize some data generated with PLUTO; however, when I run the code, it appears the following:

```python
['Bx1', 'rho']
Traceback (most recent call last):
  File "visualising_pluto.py", line 23, in <module>
    model['rho'].plot_radial_cut(0, ax=ax)
  File "/home/lance-igum/.local/lib/python3.8/site-packages/psipy/model/base.py", line 56, in __getitem__
    data = self.load_file(var)
  File "/home/lance-igum/.local/lib/python3.8/site-packages/psipy/model/pluto.py", line 32, in load_file
    return read_pluto_files(self.path, var)
  File "/home/lance-igum/.local/lib/python3.8/site-packages/psipy/io/pluto.py", line 60, in read_pluto_files
    return data.isel(time=1)
  File "/home/lance-igum/.local/lib/python3.8/site-packages/xarray/core/dataarray.py", line 1191, in isel
    variable = self._variable.isel(indexers, missing_dims=missing_dims)
  File "/home/lance-igum/.local/lib/python3.8/site-packages/xarray/core/variable.py", line 1156, in isel
    return self[key]
  File "/home/lance-igum/.local/lib/python3.8/site-packages/xarray/core/variable.py", line 777, in __getitem__
    data = as_indexable(self._data)[indexer]
  File "/home/lance-igum/.local/lib/python3.8/site-packages/xarray/core/indexing.py", line 1159, in __getitem__
    return array[key]
IndexError: index 1 is out of bounds for axis 0 with size 1
```

Do you have any idea about this issue?.

Best regards,
José

**Comment by dstansby** [comment]
Thanks for reporting. I suspect this broke when I updated `psipy` to handle multiple time steps, but perhaps didn't update the PLUTO code properley. Once https://github.com/predsci/PsiPy/issues/42 is solved it should be easier to take a look into this issue.
