### ISSUE TITLE
PLUTO- Sampling data

### ISSUE THREAD

**Issue by mbennun** [predsci/PsiPy#48]
The sampling of data does not work with PLUTO output .  This has to do with having more than one time step in the output directory.  The way the code is set now it seems as if one can interpolate between time steps - which is not obvious that we want. 
If we just want to be able to interpolate on the grid then the fix is clear.

**Comment by jj-gonzalez-aviles** [comment]
The specific error I got is the following: 

['BrR', 'Bx1', 'RHO', 'rho', 'vx1']
Traceback (most recent call last):
  File "plot_sampling_data.py", line 26, in <module>
    samples = rho_model.sample_at_coords(lon,lat,r)
  File "/home/lance-igum/.local/lib/python3.8/site-packages/astropy/units/decorators.py", line 253, in wrapper
    return_ = wrapped_function(*func_args, **func_kwargs)
  File "/home/lance-igum/.local/lib/python3.8/site-packages/psipy/model/variable.py", line 416, in sample_at_coords
    xi = np.column_stack([t,
  File "<__array_function__ internals>", line 5, in column_stack
  File "/home/lance-igum/.local/lib/python3.8/site-packages/numpy/lib/shape_base.py", line 656, in column_stack
    return _nx.concatenate(arrays, 1)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 1000
